# generated by datamodel-codegen:
#   filename:  messages.schema.json
#   timestamp: 2026-07-24T06:09:42+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )


class OsType(StrEnum):
    Windows = 'Windows'
    macOS = 'macOS'
    Android = 'Android'
    IOS = 'IOS'
    Linux = 'Linux'


class UserAgentMode(StrEnum):
    auto = 'auto'
    custom = 'custom'


class ProxyType(StrEnum):
    none = 'none'
    http = 'http'
    https = 'https'
    socks5 = 'socks5'


class WebRtc(StrEnum):
    replace = 'replace'
    disabled = 'disabled'


class ScreenResolution(StrEnum):
    custom = 'custom'
    random = 'random'


class Canvas(StrEnum):
    real = 'real'
    noise = 'noise'


class WebglMetadata(StrEnum):
    custom = 'custom'
    real = 'real'
    random = 'random'


class Fonts(StrEnum):
    default = 'default'
    custom = 'custom'


class DeviceNameMode(StrEnum):
    real = 'real'
    custom = 'custom'


class DoNotTrack(StrEnum):
    default = 'default'
    open = 'open'
    close = 'close'


class Flash(StrEnum):
    accept = 'accept'
    decline = 'decline'


class PortScanProtection(StrEnum):
    accept = 'accept'
    decline = 'decline'


class HardwareAcceleration(StrEnum):
    default = 'default'
    accept = 'accept'
    decline = 'decline'


class StationInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    station_id: UUID
    name: Annotated[str, Field(min_length=1)]
    mac_address: str | None = None
    ip_address: str | None = None
    agent_version: Annotated[str, Field(min_length=1)]
    max_concurrency: Annotated[int, Field(gt=0)]


class Platform(StrEnum):
    TIKTOK = 'TIKTOK'
    FACEBOOK = 'FACEBOOK'
    TWITTER = 'TWITTER'
    YOUTUBE = 'YOUTUBE'


class StationProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gemlogin_profile_id: Annotated[str, Field(min_length=1)]
    name: str | None = None
    platform: Platform | None = None
    gem_status: str | None = None


class RegisterMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['register']
    station: StationInfo


class HeartbeatMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['heartbeat']
    station_id: UUID
    current_load: Annotated[int, Field(ge=0)]
    ts: str
    ram_mb: float | None = None
    cpu_percent: float | None = None


class CommandAckMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['command_ack']
    command_id: UUID
    station_id: UUID
    ok: bool
    detail: str | None = None
    profile_id: str | None = None


class ProfileSyncMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['profile_sync']
    station_id: UUID
    profiles: list[StationProfile]
    all_gemlogin_ids: list[str] | None = None


class UrlStatus(StrEnum):
    LIVE = 'LIVE'
    DEAD = 'DEAD'
    INCONCLUSIVE = 'INCONCLUSIVE'


class ProfileHealth(StrEnum):
    OK = 'OK'
    CHALLENGED = 'CHALLENGED'
    BLOCKED = 'BLOCKED'
    THROTTLED = 'THROTTLED'


class JobResultMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['job_result']
    command_id: UUID
    trace_id: UUID
    job_id: UUID
    url_status: UrlStatus
    profile_health: ProfileHealth
    block_reason: str | None = None
    response_time_ms: Annotated[int | None, Field(ge=0)] = None


class CookieRefreshMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['cookie_refresh']
    station_id: UUID
    profile_id: UUID
    gemlogin_profile_id: str | None = None
    cookie: Annotated[str, Field(min_length=1)]


class Step(StrEnum):
    OPEN_BROWSER = 'OPEN_BROWSER'
    LOGIN = 'LOGIN'
    DETECT = 'DETECT'
    DONE = 'DONE'


class JobProgressMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['job_progress']
    station_id: UUID
    trace_id: UUID
    job_id: UUID
    step: Step
    detail: str | None = None
    ts: str


class RunCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['script.run']
    trace_id: UUID
    job_id: UUID
    target_url: str
    platform: Platform
    profile_id: UUID
    gemlogin_profile_id: str | None = None
    cookie: str


class BrowserOpenCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['browser.open']
    profile_id: UUID
    gemlogin_profile_id: str | None = None
    cookie: str | None = None


class BrowserCloseCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['browser.close']
    profile_id: UUID
    gemlogin_profile_id: str | None = None


class ProfileDeleteCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['profile.delete']
    gemlogin_profile_id: Annotated[str, Field(min_length=1)]


class Method(StrEnum):
    COOKIE = 'COOKIE'
    INFO = 'INFO'
    USERPASS = 'USERPASS'


class LoginRunCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['login.run']
    profile_id: UUID
    gemlogin_profile_id: str | None = None
    platform: Platform
    method: Method
    cookie: str | None = None
    username: str | None = None
    password: str | None = None
    otp_secret: str | None = None
    confirm_username: str | None = None
    hotmail_email: str | None = None
    hotmail_password: str | None = None
    hotmail_token: str | None = None


class Action(StrEnum):
    START = 'START'
    STOP = 'STOP'


class CdpForwardCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['cdp.forward']
    action: Action
    session_id: UUID
    profile_id: UUID | None = None
    gemlogin_profile_id: str | None = None


class RegisteredMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['registered']
    station_id: UUID


class CheckJobMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trace_id: UUID
    job_id: UUID
    target_url: str
    url_hash: str
    platform: Platform
    retry_count: Annotated[int | None, Field(ge=0)] = 0


class ProfileConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    os_type: OsType | None = 'macOS'
    os_version: str | None = 'macos13'
    browser_version: str | None = '141'
    startup_url: str | None = ''
    user_agent_mode: UserAgentMode | None = 'auto'
    user_agent: str | None = None
    country: str | None = 'Vietnam'
    language: str | None = 'vi,en'
    time_zone: str | None = 'Asia/Ho_Chi_Minh'
    proxy_type: ProxyType | None = 'none'
    proxy: str | None = None
    web_rtc: WebRtc | None = 'disabled'
    screen_resolution: ScreenResolution | None = 'random'
    resolution: str | None = '1920x1080'
    canvas: Canvas | None = 'noise'
    webgl_image: Canvas | None = 'noise'
    webgl_metadata: WebglMetadata | None = 'custom'
    webgl_vendor: str | None = None
    webgl_renderer: str | None = None
    audio_context: Canvas | None = 'noise'
    media_device: Canvas | None = 'noise'
    client_rects: Canvas | None = 'noise'
    fonts: Fonts | None = 'default'
    speech_voices: Canvas | None = 'noise'
    ssl: Canvas | None = 'real'
    plugins: Canvas | None = 'noise'
    hardware_concurrency: Annotated[int | None, Field(gt=0)] = 10
    device_memory: Annotated[int | None, Field(gt=0)] = 10
    device_name_mode: DeviceNameMode | None = 'custom'
    device_name: str | None = None
    mac_address_mode: DeviceNameMode | None = 'custom'
    mac_address: str | None = None
    do_not_track: DoNotTrack | None = 'open'
    flash: Flash | None = 'accept'
    port_scan_protection: PortScanProtection | None = 'accept'
    hardware_acceleration: HardwareAcceleration | None = 'accept'


class ProfileCreateCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['profile.create']
    platform: Platform | None = None
    account_label: str | None = None
    proxy: str | None = None
    config: ProfileConfig | None = None


class ProfileUpdateCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal['profile.update']
    gemlogin_profile_id: Annotated[str, Field(min_length=1)]
    account_label: str | None = None
    proxy: str | None = None
    config: ProfileConfig | None = None


class ServerCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['command']
    command_id: UUID
    command: (
        RunCommand
        | BrowserOpenCommand
        | BrowserCloseCommand
        | ProfileCreateCommand
        | ProfileUpdateCommand
        | ProfileDeleteCommand
        | LoginRunCommand
        | CdpForwardCommand
    )
